package com.greenhouse.environnement.config;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import org.springframework.stereotype.Component;

/**
 * Custom business metrics for greenhouse monitoring.
 * Exposes metrics to Prometheus via Micrometer.
 */
@Component
public class MetricsConfig {

    private final MeterRegistry meterRegistry;

    public MetricsConfig(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }

    /**
     * Counter for total measurements recorded by type.
     */
    public Counter measurementCounter(String type) {
        return Counter.builder("greenhouse.measurements.total")
                .tag("type", type)
                .description("Total number of measurements recorded")
                .register(meterRegistry);
    }

    /**
     * Counter for alerts generated by type and severity.
     */
    public Counter alertCounter(String type, String severity) {
        return Counter.builder("greenhouse.alerts.total")
                .tag("type", type)
                .tag("severity", severity)
                .description("Total number of alerts generated")
                .register(meterRegistry);
    }

    /**
     * Timer for Kafka message publishing latency.
     */
    public Timer kafkaPublishTimer() {
        return Timer.builder("greenhouse.kafka.publish.duration")
                .description("Time taken to publish messages to Kafka")
                .register(meterRegistry);
    }

    /**
     * Increment measurement counter.
     */
    public void incrementMeasurement(String type) {
        measurementCounter(type).increment();
    }

    /**
     * Increment alert counter.
     */
    public void incrementAlert(String type, String severity) {
        alertCounter(type, severity).increment();
    }
}
